// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUS0c2NzCh7eVRFr6MaRMKGEk8R48shpA',
    appId: '1:455793880562:web:4ab80bcd9657f50fc08f6b',
    messagingSenderId: '455793880562',
    projectId: 'unimarket-6dd38',
    authDomain: 'unimarket-6dd38.firebaseapp.com',
    storageBucket: 'unimarket-6dd38.firebasestorage.app',
    measurementId: 'G-XP1P4160RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFerp5CJF5kmPGbXOX1lsMAL5kjixpYc',
    appId: '1:455793880562:android:2e6d64dd1a568da6c08f6b',
    messagingSenderId: '455793880562',
    projectId: 'unimarket-6dd38',
    storageBucket: 'unimarket-6dd38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgn1A_kusRPk_u1BsXRsnY2yBXUvxSun8',
    appId: '1:455793880562:ios:fbc772b61d553144c08f6b',
    messagingSenderId: '455793880562',
    projectId: 'unimarket-6dd38',
    storageBucket: 'unimarket-6dd38.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgn1A_kusRPk_u1BsXRsnY2yBXUvxSun8',
    appId: '1:455793880562:ios:fbc772b61d553144c08f6b',
    messagingSenderId: '455793880562',
    projectId: 'unimarket-6dd38',
    storageBucket: 'unimarket-6dd38.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUS0c2NzCh7eVRFr6MaRMKGEk8R48shpA',
    appId: '1:455793880562:web:243315960f0f8b0fc08f6b',
    messagingSenderId: '455793880562',
    projectId: 'unimarket-6dd38',
    authDomain: 'unimarket-6dd38.firebaseapp.com',
    storageBucket: 'unimarket-6dd38.firebasestorage.app',
    measurementId: 'G-5YHCRSQK95',
  );
}
